### ISSUE TITLE
:sparkles: Add support for Docker secrets

### ISSUE THREAD

**Issue by linkdd** [SaaShup/netbox-docker-agent#177]
## Context

I have a Docker container that expects a file in `/run/secrets/admin_password` (it is hard-coded).

In Docker Compose, this is done using:

```yaml
secrets:
  admin_password:
    file: ./myadminpwd.txt

services:
  myservice:
    image: ...
    secrets:
      - admin_password
```

Though, `docker run` does not support secrets, as it is a feature only available with Docker Swarm. I wonder how Docker Compose implements it (do they simply bind-mount the file or do they initialize a Swarm?).

Does it make sense to have the Netbox Docker Agent initialize a Swarm on the host it runs on?

## Feature Request

I would need a way to specify, when creating a container, a secret either from:

 - a file on the host
 - a base64 encoded string

If you consider that I should just "bind mount a file" and handle securing that file myself, feel free to close this feature request.
